### ISSUE TITLE
一些配置的疑问

### ISSUE THREAD

**Issue by Andowa** [walkingon/chatgpt_buddy#1]
国内配置中，API2D代理的api可以用chatgpt官方的api值吗？
我输入官方的api值后，
报错
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No response from OpenAI API".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by walkingon** [comment]
不可以，api和key要对应的。使用API2D的API就要使用API2D上申请的Forward Key

**Comment by Andowa** [comment]
> 不可以，api和key要对应的。使用API2D的API就要使用API2D上申请的Forward Key

好的，谢谢。
